### PR TITLE
issue#140 .nvmrc to autoswitch terminal from node7 to node6

### PR DESCRIPTION
**Pull request by Falieson**
Automatically switch from node7/yarn to node6 when entering the crater directory. Will follow up this MR to update the Readme.md once https://github.com/jcoreio/crater/pull/142 is merged.
https://github.com/creationix/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file

### CODE REVIEW

**Comment by jedwards1211** [comment]
As I mentioned in another issue, some users may want to run Crater with node 4 or 5, but this would practically force them to run it with 6.10. Let's keep .nvmrc out of this repo, of course you can still have it and gitignore it in your own working copy.  I'll check if I can add `engines` to `package.json` though to prevent it from being run with node 7+

**Comment by jedwards1211** [comment]
Hmmm, `engines` doesn't work.  I'll just make my scripts warn if they detect node 7+ I guess

**Comment by jedwards1211** [comment]
I need to merge the webpack2 stuff into master...there's a weird coverage decrease issue that I had intended to figure out first...

**Comment by Falieson** [comment]
The other PR where we discuss and close this issue https://github.com/jcoreio/crater/pull/142

**Pull request closed without merging**
